version: "3"
services:
  pdfutil:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./conf:/app/conf
      - ./cache:/app/cache
      - ./templates:/app/templates